### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by E-Zuo** [jangxx/twitch-auto-recorder-3000#2]
[issue.txt](https://github.com/jangxx/twitch-auto-recorder-3000/files/10221358/issue.txt)
python version: 3.7.0
pip all downloaded

Everything is done, and I type "python main.py".

**from typing import Generic, Optional, OrderedDict as TOrderedDict, TypeVar
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\User\AppData\Local\Programs\Python\Python37\lib\typing.py)**

Then I got this(last) error, how do I solve it?
Should I use higher python version?

**Comment by jangxx** [comment]
Looking at the stacktrace it looks like the error is not thrown within my code, but within streamlink. I tried googling the issue but couldn't really find anything about this particular problem with streamlink. Can you try just running the standalone `streamlink` command within the same venv to see if it works? If it doesn't we can raise this issue with the developers of that project.

Other than that you can try to update python to at least the latest patch version, since you're still running 3.7.0, while 3.7.16 is the latest release from the 3.7 family. Or if you have the option you can of course also just update to any newer version as well. I don't have any issues running it with python 3.7 on my own machine, but updating to a newer one usually doesn't hurt.

**Comment by E-Zuo** [comment]
Yes, I run only "streamlink" in venv

```
(venv) D:\twitch_auto_recorder_3000\twitch-auto-recorder-3000>streamlink
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\Scripts\streamlink.exe\__main__.py", line 4, in <module>
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink_cli\main.py", line 20, in <module>
    import streamlink.logger as logger
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\__init__.py", line 19, in <module>
    from streamlink.api import streams
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\plugin\api\__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\plugin\api\http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\utils\__init__.py", line 1, in <module>
    from streamlink.utils.cache import LRUCache
  File "d:\twitch_auto_recorder_3000\twitch-auto-recorder-3000\venv\lib\site-packages\streamlink\utils\cache.py", line 2, in <module>
    from typing import Generic, Optional, OrderedDict as TOrderedDict, TypeVar
ImportError: cannot import name 'OrderedDict' from 'typing' (C:\Users\User\AppData\Local\Programs\Python\Python37\lib\typing.py)
```
I will try to upgrade my python to 3.7.16 first, thank you.
(I got some problem when I use 3.11.0, so that's why I use 3.7.0)

**Comment by E-Zuo** [comment]
Okay I try 3.7.16, it work, thank you.
